//Item chọn hình thức hóa đơn
export const itemHinhThucHoaDon = [
  {
    key: 'default',
    label: 'Chọn loại hình',
    disabled: true,
  },
  {
    key: '1',
    label: 'Mua mới',
  },
  {
    key: '2',
    label: 'Sửa chữa',
  },
  {
    key: '3',
    label: 'Mực in',
  },
  {
    key: '4',
    label: 'Photo',
  },
  {
    key: '5',
    label: 'BTĐ',
  },
  {
    key: '5',
    label: 'Fast',
  },
  {
    key: '6',
    label: 'Phần mềm',
  },
  {
    key: '7',
    label: 'Linh kiện',
  },
  {
    key: '8',
    label: 'Tiếp khách',
  },
];

//--------------------------------------------------------------------------
export const headLabel = {
  invoice: [
    { id: 'soHd', label: 'Số HĐ', minWidth: 80 },
    { id: 'kyHieuHd', label: 'Ký Hiệu' },
    { id: 'ngayHd', label: 'Ngày', minWidth: 120 },
    { id: 'tenNcc', label: 'Tên NCC', minWidth: 150 },
    { id: 'noiDung', label: 'Nội Dung' },
    { id: 'tienThue', label: 'Vat' },
    { id: 'tongTien', label: 'Tổng Tiền' },
    { id: 'loaiHinh', label: 'Loại Hình', minWidth: 120 },
    { id: 'trong', label: '' },
  ],
  user: [
    { id: 'userName', label: 'Tên đăng nhập' },
    { id: 'fullName', label: 'Họ & tên' },
    { id: 'phone', label: 'Điện thoại' },
    { id: 'email', label: 'Email' },
    { id: 'status', label: 'Trạng thái' },
    { id: 'trong', label: '' },
  ],
  bi: [
    { id: 'title', label: 'Tên báo cáo' },
    { id: 'link', label: 'Đường dẫn' },
    { id: 'status', label: 'Trạng thái' },
    { id: '', label: '' },
  ],
  role: [
    { id: 'name', label: 'Tên vai trò' },
    { id: 'dienGiai', label: 'Mô tả' },
    { id: 'status', label: 'Trạng thái' },
    { id: '', label: '' },
  ],
  deXuat: [
    { id: 'maPhieu', label: 'Mã phiếu' },
    { id: 'tenNcc', label: 'NCC' },
    { id: 'createDate', label: 'Ngày tạo' },
    { id: 'modifiedDate', label: 'Ngày cập nhật' },
    { id: 'tongSl', label: 'Tổng số lượng' },
    { id: 'tongTT', label: 'Tổng đơn hàng' },
    { id: 'status', label: 'Trạng thái' },
    { id: '', label: '' },
  ],
  datHang: [
    { id: 'tenNhaCungCap', label: 'NCC' },
    { id: 'chiNhanh', label: 'Kho' },
    { id: 'maHang', label: 'Mã hàng' },
    { id: 'tenHang', label: 'Tên hàng' },
    { id: 'ghiChu', label: 'Ghi chú hàng hoá' },
    { id: 'thuMuaNhap', label: 'Số lượng đặt hàng' },
    { id: 'giaVon', label: 'Gía nhập từ NCC' },
    { id: 'giaBan', label: 'Gía bán' },
    { id: 'nhapChuyen', label: 'Nhập chuyển' },
    { id: 'xuatBan', label: 'Xuất bán' },
    { id: 'tonCuoi', label: 'Tồn cuối' },
    { id: 'ngayKhoDat', label: 'Thời gian kho đặt' },
    { id: 'canhBao', label: 'Cảnh báo' },
  ],
  soHoa: [
    { id: '', label: '' },
    { id: 'loaiVb', label: 'Loại văn bản' },
    { id: 'soVb', label: 'Số văn bản' },
    { id: 'ngayVb', label: 'Ngày văn bản' },
    { id: 'noiDung', label: 'Nội dung' },
    { id: 'boPhan', label: 'Bộ phận' },
    { id: 'ngayKy', label: 'Ngày ký' },
    { id: 'file', label: 'File scan đã up' },
    { id: 'trong', label: '' },
  ],
  history: [
    { id: 'userEdit', label: 'Người thao tác' },
    { id: 'description', label: 'Nội dung thay đổi' },
    { id: 'createDate', label: 'Thời gian' },
    { id: 'trong', label: '' },
  ],
  danhMucHangHoa: [
    { id: 'maHang', label: 'Mã hàng' },
    { id: 'tenHang', label: 'Tên hàng' },
    { id: 'barcode', label: 'Barcode' },
    { id: 'dvt', label: 'Đơn vị tính' },
    { id: 'vat', label: 'Mức thuế VAT đầu vào' },
    { id: 'giaVon', label: 'Giá vốn' },
    { id: 'giaBan', label: 'Giá bán' },
    { id: 'trong', label: '' },
  ],
  danhMucNcc:[
    {id:'maNcc',label:'Mã NCC'},
    {id:'tenNcc',label:'Tên NCC'},
    {id:'email',label:'Email'},
    {id:'phone',label:'Điện thoại'},
    {id:'diaChi',label:'Đia chỉ'},
    {id:'noteHd',label:'Hợp đồng'},
    {id:'status',label:'Trạng thái'},
    {id:'trong',label:''},
  ],
  boPhan: [
    { id: 'maBp', label: 'Mã bộ phận' },
    { id: 'name', label: 'Tên bộ phận' },
    { id: 'status', label: 'Trạng thái' },
    { id: 'trong', label: '' },
  ],
};
